# Generated by Django 4.0.8 on 2022-10-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cpu_nospaces',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='manu_nospaces',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
