# Generated by Django 4.0.6 on 2022-09-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('subscription_date', models.DateTimeField(auto_now_add=True, verbose_name='date subscribed')),
            ],
        ),
    ]
