# Generated by Django 4.0.6 on 2022-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedecade',
            name='decade',
        ),
        migrations.AddField(
            model_name='releasedecade',
            name='release_decade',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
